version: '3'
services:
  breeding:
    image: breeding
    container_name: breeding
    ports:
      - "443:3000"
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt/live/www.dxnnx.cc:/app/ssl
    build: .