version: '3'
services:
  breeding:
    image: breeding
    container_name: breeding
    restart: unless-stopped
    ports:
      - "443:3000"
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt/live/www.dxnnx.cc/privkey.pem:/app/ssl/privkey.pem
      - /etc/letsencrypt/live/www.dxnnx.cc/fullchain.pem:/app/ssl/fullchain.pem
    build: .