version: '3'
services:
  breeding:
    image: breeding
    container_name: breeding
    restart: unless-stopped
    ports:
      - "8000:3000"
    volumes:
      - /etc/letsencrypt/live/www.dxnnx.cc/privkey.pem:/app/ssl/privkey.pem
      - /etc/letsencrypt/live/www.dxnnx.cc/fullchain.pem:/app/ssl/fullchain.pem
    build: .
    networks:
      - dxnnx-network

networks:
  dxnnx-network:
    external: true
    name: dxnnx-network
